### ISSUE TITLE
Import Dataset into MongoDB Cluster

### ISSUE THREAD

**Issue by laurenho025** [noradunleavy/teamtech2020#1]
Finish importing Carat dataset into the MongoDB Cluster.

**Comment by sam523a** [comment]
- [x] Samantha: Connect to cluster via command line
- [ ] Debbie: Connect to cluster via command line
- [x] Samantha: Get comfortable with MongoDB commands
- [ ] Debbie: Get comfortable with MongoDB commands
- [x] Import smaller dummy dataset
- [x] Import Carat dataset

**Comment by sam523a** [comment]
Take notes here: https://docs.google.com/document/d/17CETuiTJMKpjLfa8MWSv0Su6Qp4wsO-7PZ-8pbQHW8E/edit?usp=sharing
