### ISSUE TITLE
Clean Data Based on Schema

### ISSUE THREAD

**Issue by laurenho025** [noradunleavy/teamtech2020#11]
- [x] Try converting cleaned data to Pandas DataFrame for the algorithm to use
- [ ] Look into how to put the outputted DataFrame back into Mongo (or if this is even possible)

**Comment by emilyvera** [comment]
Converted cleaned data to DataFrame as specified by the schema

**Comment by sam523a** [comment]
Moved "Look into how to put the outputted DataFrame back into Mongo (or if this is even possible)" to separate issue: #13
